# Generated by Django 3.1 on 2020-09-09 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 9, 20, 47, 49, 322405, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='productImage',
        ),
    ]
